### ISSUE TITLE
Error when using sphinxteam/Boltzmann.jl

### ISSUE THREAD

**Issue by krzakala** [sphinxteam/Boltzmann.jl#11]
Probably due to not having AppleAccelerate ?

`using Boltzmann
INFO: Precompiling module Distributions...
INFO: Recompiling stale cache file /Users/florent/.julia/lib/v0.4/ArrayViews.ji for module ArrayViews.
INFO: Recompiling stale cache file /Users/florent/.julia/lib/v0.4/StatsFuns.ji for module StatsFuns.
ERROR: LoadError: LoadError: LoadError: ArgumentError: AppleAccelerate not found in path
 in require at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/florent/.julia/v0.4/Boltzmann/src/rbm.jl, in expression starting on line 5
while loading /Users/florent/.julia/v0.4/Boltzmann/src/core.jl, in expression starting on line 3
while loading /Users/florent/.julia/v0.4/Boltzmann/src/Boltzmann.jl, in expression starting on line 21`

**Comment by krzakala** [comment]
Yes, that was it... we should try to find a way to fix this so that it does not crash..

Also, I get a 
`WARNING: deprecated syntax "!= (" at /Users/florent/.julia/v0.4/Devectorize/src/texpr.jl:226.`
Use "!=(" instead.

**Comment by krzakala** [comment]
In fact, I now get an avalanche of comments...

**Comment by eric-tramel** [comment]
So, the deal with the deprecation warnings has to do with the fact that the Devectorize.jl package has not properly "upgraded" for Julia v.0.4, and so we have all these deprecation warnings. These are just syntactical warnings, so I don't think that there is any real problem, except for the fact that it makes a mess of the console. Until that package is updated, you'll get a stream of warnings every time its used.

However, it is strange that it was crashing out at first. Maybe I didn't properly add AppleAccelerate to the required package list, though. I'll take a look at it.

**Comment by eric-tramel** [comment]
Alright, I fixed in this commit: 8f59391e638053e3e5ea2306b32cf1c855518e06 . Closing.
