### ISSUE TITLE
Any idea what this is ?

### ISSUE THREAD

**Issue by krzakala** [sphinxteam/Boltzmann.jl#16]
ERROR: LoadError: LoadError: unrecognized keyword argument "approx"
 in run_mnist at /Users/florent/.julia/v0.4/Boltzmann/test/testTAP.jl:33
 in include at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0-rc1.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/florent/.julia/v0.4/Boltzmann/test/testTAP.jl, in expression starting on line 66
while loading /Users/florent/.julia/v0.4/Boltzmann/test/runtests.jl, in expression starting on line 7

**Comment by eric-tramel** [comment]
After talking with @krzakala, it seems that this was a local artifact of how Julia loads/un-loads (or: doesn't un-load) packages.
