### ISSUE TITLE
Merging TAP

### ISSUE THREAD

**Issue by eric-tramel** [sphinxteam/Boltzmann.jl#17]
@marylou-gabrie:
So, now that it looks like the TAP learning implementation is finally in a working format, we should take a look at accomplishing the merge of the now long-suffering `implement-TAP` branch. 

Can we feature-freeze the branch and start refactoring the code to get it into the final format for the merge?

**Comment by marylou-gabrie** [comment]
"Can we feature-freeze the branch and start refactoring the code to get it into the final format for the merge? "
Obviously, I don't speak geek well enough yet. :)

**Comment by AurelienDecelle** [comment]
I think he is just speaking to himself :)

**Comment by eric-tramel** [comment]
:cry:

**Comment by eric-tramel** [comment]
Okay, so we had the TAP/EMF content merged back into the master branch, so I'm closing this issue.
